//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uretim
    {
        public Uretim()
        {
            this.Planlamas = new HashSet<Planlama>();
        }
    
        public int UNo { get; set; }
        public string UAdi { get; set; }
        public string USehir { get; set; }
        public Nullable<int> UMiktar { get; set; }
    
        public virtual ICollection<Planlama> Planlamas { get; set; }
    }
}
